package constants

const (
	LoginSuccess          string = "Login Success"
	ForgotPasswordSuccess string = "A reset password link is sent to the Registered Email ID associated with the username"
	PasswordUpdateSuccess string = "Password is successfully updated"
	VerifyTokenSuccess    string = "Token is successfully verified"
	RefreshTokenSuccess   string = "Token is successfully refreshed"
	UserBlockSuccess      string = "User is successfully blocked"
	UnauthorizedAccess    string = "Unauthorized Access"
	ResetTokenSuccess     string = "Reset token is successfully verified"
	EmailAutoGenerated    string = "Email generated successfully"
)
